name: "Tests"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"

env:
  CI: "true"

jobs:
  main:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, jruby]
    steps:
      - uses: actions/checkout@v2.0.0
        with:
          fetch-depth: 1
      - uses: ruby/setup-ruby@master
        with:
          ruby-version: ${{ matrix.ruby }}
      - run: bundle install --jobs 4 --retry 3
        name: Install Ruby deps
      - run: bundle exec rake
